services:
    ikanban_db:
        build:
            context: ./backend/
            dockerfile: ./sql/Dockerfile
        restart: always
        env_file:
          - ./backend/.env.production
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            LANG: fr_FR.UTF-8
            LC_ALL: fr_FR.UTF-8
        ports:
            - '${DB_PORT}:5432'
        volumes:
            - db-prod-data:/var/lib/postgresql/data
            - ./backend/sql:/docker-entrypoint-initdb.d

    ikanban_api:
        build:
            context: ./backend/
            dockerfile: ./Dockerfile
        restart: always
        env_file:
            - ./backend/.env.production
        ports:
          - '${PORT}:3000'
        depends_on:
            - ikanban_db
        volumes:
            - ./backend:/app
            - /app/node_modules # évite que le node_modules local écrase celui du conteneur
        command: npm run start:prod

    nginx:
        build:
          context: .
          dockerfile: ./nginx/Dockerfile
        restart: always
        ports:
          - '80:80'
        depends_on:
            - ikanban_api

volumes:
    db-prod-data:
